/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as RealtyRouteImport } from './routes/realty'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as InteriorRouteImport } from './routes/interior'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConstructionRouteImport } from './routes/construction'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RealtySlugRouteImport } from './routes/realty.$slug'
import { Route as ProjectsConstructionRouteImport } from './routes/projects.construction'
import { Route as InteriorSlugRouteImport } from './routes/interior.$slug'
import { Route as ConstructionCostEstimatorRouteImport } from './routes/construction.cost-estimator'
import { Route as ConstructionSlugRouteImport } from './routes/construction.$slug'
import { Route as AdminProjectsRouteImport } from './routes/admin.projects'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const RealtyRoute = RealtyRouteImport.update({
  id: '/realty',
  path: '/realty',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const InteriorRoute = InteriorRouteImport.update({
  id: '/interior',
  path: '/interior',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConstructionRoute = ConstructionRouteImport.update({
  id: '/construction',
  path: '/construction',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RealtySlugRoute = RealtySlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => RealtyRoute,
} as any)
const ProjectsConstructionRoute = ProjectsConstructionRouteImport.update({
  id: '/construction',
  path: '/construction',
  getParentRoute: () => ProjectsRoute,
} as any)
const InteriorSlugRoute = InteriorSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => InteriorRoute,
} as any)
const ConstructionCostEstimatorRoute =
  ConstructionCostEstimatorRouteImport.update({
    id: '/cost-estimator',
    path: '/cost-estimator',
    getParentRoute: () => ConstructionRoute,
  } as any)
const ConstructionSlugRoute = ConstructionSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ConstructionRoute,
} as any)
const AdminProjectsRoute = AdminProjectsRouteImport.update({
  id: '/admin/projects',
  path: '/admin/projects',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/construction': typeof ConstructionRouteWithChildren
  '/contact': typeof ContactRoute
  '/interior': typeof InteriorRouteWithChildren
  '/projects': typeof ProjectsRouteWithChildren
  '/realty': typeof RealtyRouteWithChildren
  '/services': typeof ServicesRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/construction/$slug': typeof ConstructionSlugRoute
  '/construction/cost-estimator': typeof ConstructionCostEstimatorRoute
  '/interior/$slug': typeof InteriorSlugRoute
  '/projects/construction': typeof ProjectsConstructionRoute
  '/realty/$slug': typeof RealtySlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/construction': typeof ConstructionRouteWithChildren
  '/contact': typeof ContactRoute
  '/interior': typeof InteriorRouteWithChildren
  '/projects': typeof ProjectsRouteWithChildren
  '/realty': typeof RealtyRouteWithChildren
  '/services': typeof ServicesRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/construction/$slug': typeof ConstructionSlugRoute
  '/construction/cost-estimator': typeof ConstructionCostEstimatorRoute
  '/interior/$slug': typeof InteriorSlugRoute
  '/projects/construction': typeof ProjectsConstructionRoute
  '/realty/$slug': typeof RealtySlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/construction': typeof ConstructionRouteWithChildren
  '/contact': typeof ContactRoute
  '/interior': typeof InteriorRouteWithChildren
  '/projects': typeof ProjectsRouteWithChildren
  '/realty': typeof RealtyRouteWithChildren
  '/services': typeof ServicesRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/construction/$slug': typeof ConstructionSlugRoute
  '/construction/cost-estimator': typeof ConstructionCostEstimatorRoute
  '/interior/$slug': typeof InteriorSlugRoute
  '/projects/construction': typeof ProjectsConstructionRoute
  '/realty/$slug': typeof RealtySlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/construction'
    | '/contact'
    | '/interior'
    | '/projects'
    | '/realty'
    | '/services'
    | '/admin/projects'
    | '/construction/$slug'
    | '/construction/cost-estimator'
    | '/interior/$slug'
    | '/projects/construction'
    | '/realty/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/construction'
    | '/contact'
    | '/interior'
    | '/projects'
    | '/realty'
    | '/services'
    | '/admin/projects'
    | '/construction/$slug'
    | '/construction/cost-estimator'
    | '/interior/$slug'
    | '/projects/construction'
    | '/realty/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/construction'
    | '/contact'
    | '/interior'
    | '/projects'
    | '/realty'
    | '/services'
    | '/admin/projects'
    | '/construction/$slug'
    | '/construction/cost-estimator'
    | '/interior/$slug'
    | '/projects/construction'
    | '/realty/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ConstructionRoute: typeof ConstructionRouteWithChildren
  ContactRoute: typeof ContactRoute
  InteriorRoute: typeof InteriorRouteWithChildren
  ProjectsRoute: typeof ProjectsRouteWithChildren
  RealtyRoute: typeof RealtyRouteWithChildren
  ServicesRoute: typeof ServicesRoute
  AdminProjectsRoute: typeof AdminProjectsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/realty': {
      id: '/realty'
      path: '/realty'
      fullPath: '/realty'
      preLoaderRoute: typeof RealtyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interior': {
      id: '/interior'
      path: '/interior'
      fullPath: '/interior'
      preLoaderRoute: typeof InteriorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/construction': {
      id: '/construction'
      path: '/construction'
      fullPath: '/construction'
      preLoaderRoute: typeof ConstructionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/realty/$slug': {
      id: '/realty/$slug'
      path: '/$slug'
      fullPath: '/realty/$slug'
      preLoaderRoute: typeof RealtySlugRouteImport
      parentRoute: typeof RealtyRoute
    }
    '/projects/construction': {
      id: '/projects/construction'
      path: '/construction'
      fullPath: '/projects/construction'
      preLoaderRoute: typeof ProjectsConstructionRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/interior/$slug': {
      id: '/interior/$slug'
      path: '/$slug'
      fullPath: '/interior/$slug'
      preLoaderRoute: typeof InteriorSlugRouteImport
      parentRoute: typeof InteriorRoute
    }
    '/construction/cost-estimator': {
      id: '/construction/cost-estimator'
      path: '/cost-estimator'
      fullPath: '/construction/cost-estimator'
      preLoaderRoute: typeof ConstructionCostEstimatorRouteImport
      parentRoute: typeof ConstructionRoute
    }
    '/construction/$slug': {
      id: '/construction/$slug'
      path: '/$slug'
      fullPath: '/construction/$slug'
      preLoaderRoute: typeof ConstructionSlugRouteImport
      parentRoute: typeof ConstructionRoute
    }
    '/admin/projects': {
      id: '/admin/projects'
      path: '/admin/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AdminProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ConstructionRouteChildren {
  ConstructionSlugRoute: typeof ConstructionSlugRoute
  ConstructionCostEstimatorRoute: typeof ConstructionCostEstimatorRoute
}

const ConstructionRouteChildren: ConstructionRouteChildren = {
  ConstructionSlugRoute: ConstructionSlugRoute,
  ConstructionCostEstimatorRoute: ConstructionCostEstimatorRoute,
}

const ConstructionRouteWithChildren = ConstructionRoute._addFileChildren(
  ConstructionRouteChildren,
)

interface InteriorRouteChildren {
  InteriorSlugRoute: typeof InteriorSlugRoute
}

const InteriorRouteChildren: InteriorRouteChildren = {
  InteriorSlugRoute: InteriorSlugRoute,
}

const InteriorRouteWithChildren = InteriorRoute._addFileChildren(
  InteriorRouteChildren,
)

interface ProjectsRouteChildren {
  ProjectsConstructionRoute: typeof ProjectsConstructionRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsConstructionRoute: ProjectsConstructionRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

interface RealtyRouteChildren {
  RealtySlugRoute: typeof RealtySlugRoute
}

const RealtyRouteChildren: RealtyRouteChildren = {
  RealtySlugRoute: RealtySlugRoute,
}

const RealtyRouteWithChildren =
  RealtyRoute._addFileChildren(RealtyRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ConstructionRoute: ConstructionRouteWithChildren,
  ContactRoute: ContactRoute,
  InteriorRoute: InteriorRouteWithChildren,
  ProjectsRoute: ProjectsRouteWithChildren,
  RealtyRoute: RealtyRouteWithChildren,
  ServicesRoute: ServicesRoute,
  AdminProjectsRoute: AdminProjectsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
