/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as RealtyRouteImport } from './routes/realty'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as PlotsForSaleInLohegaonPuneRouteImport } from './routes/plots-for-sale-in-lohegaon-pune'
import { Route as InteriorRouteImport } from './routes/interior'
import { Route as FlatsInLohegaonPuneRouteImport } from './routes/flats-in-lohegaon-pune'
import { Route as FlatsForRentInLohegaonPuneRouteImport } from './routes/flats-for-rent-in-lohegaon-pune'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConstructionRouteImport } from './routes/construction'
import { Route as AboutRouteImport } from './routes/about'
import { Route as R2BhkFlatsInLohegaonPuneRouteImport } from './routes/2-bhk-flats-in-lohegaon-pune'
import { Route as IndexRouteImport } from './routes/index'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const RealtyRoute = RealtyRouteImport.update({
  id: '/realty',
  path: '/realty',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const PlotsForSaleInLohegaonPuneRoute =
  PlotsForSaleInLohegaonPuneRouteImport.update({
    id: '/plots-for-sale-in-lohegaon-pune',
    path: '/plots-for-sale-in-lohegaon-pune',
    getParentRoute: () => rootRouteImport,
  } as any)
const InteriorRoute = InteriorRouteImport.update({
  id: '/interior',
  path: '/interior',
  getParentRoute: () => rootRouteImport,
} as any)
const FlatsInLohegaonPuneRoute = FlatsInLohegaonPuneRouteImport.update({
  id: '/flats-in-lohegaon-pune',
  path: '/flats-in-lohegaon-pune',
  getParentRoute: () => rootRouteImport,
} as any)
const FlatsForRentInLohegaonPuneRoute =
  FlatsForRentInLohegaonPuneRouteImport.update({
    id: '/flats-for-rent-in-lohegaon-pune',
    path: '/flats-for-rent-in-lohegaon-pune',
    getParentRoute: () => rootRouteImport,
  } as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConstructionRoute = ConstructionRouteImport.update({
  id: '/construction',
  path: '/construction',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const R2BhkFlatsInLohegaonPuneRoute =
  R2BhkFlatsInLohegaonPuneRouteImport.update({
    id: '/2-bhk-flats-in-lohegaon-pune',
    path: '/2-bhk-flats-in-lohegaon-pune',
    getParentRoute: () => rootRouteImport,
  } as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/2-bhk-flats-in-lohegaon-pune': typeof R2BhkFlatsInLohegaonPuneRoute
  '/about': typeof AboutRoute
  '/construction': typeof ConstructionRoute
  '/contact': typeof ContactRoute
  '/flats-for-rent-in-lohegaon-pune': typeof FlatsForRentInLohegaonPuneRoute
  '/flats-in-lohegaon-pune': typeof FlatsInLohegaonPuneRoute
  '/interior': typeof InteriorRoute
  '/plots-for-sale-in-lohegaon-pune': typeof PlotsForSaleInLohegaonPuneRoute
  '/projects': typeof ProjectsRoute
  '/realty': typeof RealtyRoute
  '/services': typeof ServicesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/2-bhk-flats-in-lohegaon-pune': typeof R2BhkFlatsInLohegaonPuneRoute
  '/about': typeof AboutRoute
  '/construction': typeof ConstructionRoute
  '/contact': typeof ContactRoute
  '/flats-for-rent-in-lohegaon-pune': typeof FlatsForRentInLohegaonPuneRoute
  '/flats-in-lohegaon-pune': typeof FlatsInLohegaonPuneRoute
  '/interior': typeof InteriorRoute
  '/plots-for-sale-in-lohegaon-pune': typeof PlotsForSaleInLohegaonPuneRoute
  '/projects': typeof ProjectsRoute
  '/realty': typeof RealtyRoute
  '/services': typeof ServicesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/2-bhk-flats-in-lohegaon-pune': typeof R2BhkFlatsInLohegaonPuneRoute
  '/about': typeof AboutRoute
  '/construction': typeof ConstructionRoute
  '/contact': typeof ContactRoute
  '/flats-for-rent-in-lohegaon-pune': typeof FlatsForRentInLohegaonPuneRoute
  '/flats-in-lohegaon-pune': typeof FlatsInLohegaonPuneRoute
  '/interior': typeof InteriorRoute
  '/plots-for-sale-in-lohegaon-pune': typeof PlotsForSaleInLohegaonPuneRoute
  '/projects': typeof ProjectsRoute
  '/realty': typeof RealtyRoute
  '/services': typeof ServicesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/2-bhk-flats-in-lohegaon-pune'
    | '/about'
    | '/construction'
    | '/contact'
    | '/flats-for-rent-in-lohegaon-pune'
    | '/flats-in-lohegaon-pune'
    | '/interior'
    | '/plots-for-sale-in-lohegaon-pune'
    | '/projects'
    | '/realty'
    | '/services'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/2-bhk-flats-in-lohegaon-pune'
    | '/about'
    | '/construction'
    | '/contact'
    | '/flats-for-rent-in-lohegaon-pune'
    | '/flats-in-lohegaon-pune'
    | '/interior'
    | '/plots-for-sale-in-lohegaon-pune'
    | '/projects'
    | '/realty'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/2-bhk-flats-in-lohegaon-pune'
    | '/about'
    | '/construction'
    | '/contact'
    | '/flats-for-rent-in-lohegaon-pune'
    | '/flats-in-lohegaon-pune'
    | '/interior'
    | '/plots-for-sale-in-lohegaon-pune'
    | '/projects'
    | '/realty'
    | '/services'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R2BhkFlatsInLohegaonPuneRoute: typeof R2BhkFlatsInLohegaonPuneRoute
  AboutRoute: typeof AboutRoute
  ConstructionRoute: typeof ConstructionRoute
  ContactRoute: typeof ContactRoute
  FlatsForRentInLohegaonPuneRoute: typeof FlatsForRentInLohegaonPuneRoute
  FlatsInLohegaonPuneRoute: typeof FlatsInLohegaonPuneRoute
  InteriorRoute: typeof InteriorRoute
  PlotsForSaleInLohegaonPuneRoute: typeof PlotsForSaleInLohegaonPuneRoute
  ProjectsRoute: typeof ProjectsRoute
  RealtyRoute: typeof RealtyRoute
  ServicesRoute: typeof ServicesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/realty': {
      id: '/realty'
      path: '/realty'
      fullPath: '/realty'
      preLoaderRoute: typeof RealtyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plots-for-sale-in-lohegaon-pune': {
      id: '/plots-for-sale-in-lohegaon-pune'
      path: '/plots-for-sale-in-lohegaon-pune'
      fullPath: '/plots-for-sale-in-lohegaon-pune'
      preLoaderRoute: typeof PlotsForSaleInLohegaonPuneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interior': {
      id: '/interior'
      path: '/interior'
      fullPath: '/interior'
      preLoaderRoute: typeof InteriorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flats-in-lohegaon-pune': {
      id: '/flats-in-lohegaon-pune'
      path: '/flats-in-lohegaon-pune'
      fullPath: '/flats-in-lohegaon-pune'
      preLoaderRoute: typeof FlatsInLohegaonPuneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flats-for-rent-in-lohegaon-pune': {
      id: '/flats-for-rent-in-lohegaon-pune'
      path: '/flats-for-rent-in-lohegaon-pune'
      fullPath: '/flats-for-rent-in-lohegaon-pune'
      preLoaderRoute: typeof FlatsForRentInLohegaonPuneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/construction': {
      id: '/construction'
      path: '/construction'
      fullPath: '/construction'
      preLoaderRoute: typeof ConstructionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/2-bhk-flats-in-lohegaon-pune': {
      id: '/2-bhk-flats-in-lohegaon-pune'
      path: '/2-bhk-flats-in-lohegaon-pune'
      fullPath: '/2-bhk-flats-in-lohegaon-pune'
      preLoaderRoute: typeof R2BhkFlatsInLohegaonPuneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R2BhkFlatsInLohegaonPuneRoute: R2BhkFlatsInLohegaonPuneRoute,
  AboutRoute: AboutRoute,
  ConstructionRoute: ConstructionRoute,
  ContactRoute: ContactRoute,
  FlatsForRentInLohegaonPuneRoute: FlatsForRentInLohegaonPuneRoute,
  FlatsInLohegaonPuneRoute: FlatsInLohegaonPuneRoute,
  InteriorRoute: InteriorRoute,
  PlotsForSaleInLohegaonPuneRoute: PlotsForSaleInLohegaonPuneRoute,
  ProjectsRoute: ProjectsRoute,
  RealtyRoute: RealtyRoute,
  ServicesRoute: ServicesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
